// <auto-generated />
using System;
using JobAdsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobAdsAPI.Migrations
{
    [DbContext(typeof(JobAdDbContext))]
    [Migration("20250518160332_ChangedLocation")]
    partial class ChangedLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("JobAdsAPI.Models.JobAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpierienceLevel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCSharpMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDotNetMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSQLMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherSkills")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobAds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Tech Corp",
                            ExpierienceLevel = "Mid",
                            IsCSharpMentioned = true,
                            IsDotNetMentioned = true,
                            IsSQLMentioned = false,
                            JobRole = "Backend",
                            JobTitle = "Software Engineer",
                            Location = "Oslo",
                            OtherSkills = "Azure, Docker",
                            PublishedAt = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkType = "Remote"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Web Solutions",
                            ExpierienceLevel = "Junior",
                            IsCSharpMentioned = false,
                            IsDotNetMentioned = false,
                            IsSQLMentioned = false,
                            JobRole = "Frontend",
                            JobTitle = "Frontend Developer",
                            Location = "Bergen",
                            OtherSkills = "React, JavaScript",
                            PublishedAt = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkType = "Hybrid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
