// <auto-generated />
using System;
using JobAdsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobAdsAPI.Migrations
{
    [DbContext(typeof(JobAdDbContext))]
    [Migration("20250516092637_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("JobAdsAPI.Models.JobAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpierienceLevel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCSharpMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDotNetMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSQLMentioned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherSkills")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobAds");
                });
#pragma warning restore 612, 618
        }
    }
}
